### ISSUE TITLE
Deprecate in favor of grunt-assets-inline?

### ISSUE THREAD

**Issue by Trott** [Trott/grunt-html-smoosher#31]
I don't use grunt anymore so it's hard for me to get too excited about maintaining this package. https://www.npmjs.com/package/grunt-assets-inline looks like it might be better maintained and seems to be in wider user. Should `grunt-html-smoosher` be deprecated and people directed to `grunt-assets-inline`? It started as a fork of `grunt-html-smoosher` so it should be fairly compatible.

/ping @sparanoid Is `grunt-assets-inline` still maintained and do you plan to maintain it for the foreseeable future?

**Comment by sparanoid** [comment]
I still use `grunt-assets-inline` and maintain it. but now I only maintain it for bug and security fixes. That means there won't be any new feature for this project for the foreseeable future.

However, I don't recommend redirect `grunt-html-smoosher` to `grunt-assets-inline`. I've changed [a lot](https://github.com/sparanoid/grunt-assets-inline/compare/f05fedfebd60e903425fcb6dcea9cba986318c2e...master) of the original implementation so it won't work out of the box for `grunt-html-smoosher` users. That's why I start a new project with your credits in readme instead of forking `grunt-html-smoosher`. 😀
